[profile.default]
src = "programs"
out = "target"
scripts = ["tests/meridian.ts"]

[rpc_endpoints]
devnet = "https://api.devnet.solana.com"

[programs.devnet]
collateral_vault = "BE8LMagbTc3Rcy6UV6NDyCSfSSygZ5k9fB1v4WPBmfwb"
credit_engine = "3vERhcczWPCJLhw6RygnbJAwzFKywbFwwB2efnXefAPE"
bnpl_checkout = "7SDq9q5JrKZGHvaz5dcgHpzAFy5LP583BGHJuyExHPnX"
repayment_tracker = "4fkfzDbGdpyRtAByZWQ4xskB6AKfpHtFwy8mTTNx7V1G"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
